name: 'Setup'
description: 'Setup environment with Java 21'
runs:
  using: 'composite'
  steps:
    - name: 'Setup: Java 21'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21.x'
    - name: 'Setup: check tools'
      shell: bash
      run: |
        java -version
